name: Maven Package and Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file StudentManagementSystem2/pom.xml

    - name: Build Docker image
      run: docker build -t kvpvishnu11/my-app-image:latest StudentManagementSystem2/

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      env:
        DOCKER_CLI_ASK_PASS: ""

    - name: Push Docker image to Docker Hub
      run: docker push kvpvishnu11/sms:latest
